# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - watertemp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/anntykk/watertemp-service/
        username: ${{ secrets.AzureAppService_ContainerUsername_c098693afb094d74aacdbf5a589080ae }}
        password: ${{ secrets.AzureAppService_ContainerPassword_907f44e39f69474d9f0786bf71e36265 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/anntykk/watertemp-service/${{ secrets.AzureAppService_ContainerUsername_c098693afb094d74aacdbf5a589080ae }}/latest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'watertemp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b76669cce1a2466f8c9323d428a9b5fb }}
        images: 'ghcr.io/anntykk/watertemp-service/${{ secrets.AzureAppService_ContainerUsername_c098693afb094d74aacdbf5a589080ae }}/latest:${{ github.sha }}'